version: 1.0.0.{build}
branches:
  except:
  - pages
configuration: Release
clone_folder: C:\projects\SparkPost
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  nuget_user: user@bricksandmortarstudio.com
  nuget_password: aHlingenDPOt
install:
- ps: >-
    Write-Host $env:APPVEYOR_REPO_BRANCH;
    If ($env:APPVEYOR_REPO_BRANCH -is "master"){
    nuget sources add -Name "Rock Master" -Source https://ci.appveyor.com/nuget/bricks-Rock-master
    Write-Host "Using Master";
    }

    Else{
    nuget sources add -Name "Rock Develop" -Source https://ci.appveyor.com/nuget/bricks-rock-develop
    Write-Host "Using Develop";
    }
before_build:
- cmd: nuget restore C:\projects\SparkPost\SparkPost.sln
build:
  verbosity: minimal
after_build:
- ps: >-
    #The path for the staging directory

    $path = $env:APPVEYOR_BUILD_FOLDER+'\out'

    #Regex for stripping directory leads for Rock .lst files

    $regex = '^(\.*\\*\.)*'


    New-Item $path -type directory

    New-Item $path\content -type directory

    New-Item $path\uninstall -type directory

    New-Item $path\content\bin -type directory

    New-Item $path\content\Webhooks -type directory



    Copy-Item $env:APPVEYOR_BUILD_FOLDER\SparkPost\bin\Release\com.bricksandmortarstudio.SparkPost.dll $path\content\bin\

    Copy-Item $env:APPVEYOR_BUILD_FOLDER\SparkPost\Webhooks\SparkPost.ashx $path\content\Webhooks


    Get-ChildItem $path\content\*.* -Recurse | Resolve-Path -Relative | Set-Content $path\uninstall\deletefile.lst

    (Get-Content $path\uninstall\deletefile.lst) -replace $regex, '' | Set-Content $path\uninstall\deletefile.lst


    $name = $env:APPVEYOR_PROJECT_NAME+'-v'+$env:APPVEYOR_BUILD_VERSION+'.plugin'


    $command = 'cmd.exe /C  7z a -tzip -r ' + $path + '\' + $name + ' ' + $path + '\*'


    Invoke-Expression -Command:$command

    Get-ChildItem $path/*.plugin| % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
    Push-AppveyorArtifact $path\content\bin\com.bricksandmortarstudio.SparkPost.dll
test: off
artifacts:
- path: '**\*.plugin'
  name: Plugin
deploy:
- provider: GitHub
  tag:
  release: Version $(appveyor_build_version)
  description: Description
  auth_token:
    secure: purnbQq+/7nii64HdaMRg++QQARjdTJ3VYVIq8EQBR7NxrTp46pw+JIxLjbL/obW
  artifact: /.*\.plugin/
  draft: true
  prerelease: false
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true

- provider: Environment
  name: Hope
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
